version: '3.8'

services:
  postgres-flyway:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flyway_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mohammad

  flyway:
    image: flyway/flyway:9.22.3
    command: -configFiles=/flyway/flyway.conf migrate
    volumes:
      - ./flyway/sql:/sql                 # Mount SQL scripts
      - ./flyway/flyway.conf:/flyway/flyway.conf  # Correct path to conf
    depends_on:
      - postgres-flyway
