
# version: '3.8'

# services:
#   postgres-flyway:
#     image: postgres:15
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: flyway_test_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: Mohammad


version: '3.8'

services:
  postgres-flyway:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flyway_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mohammad

  flyway:
    image: flyway/flyway:9.22.3
    command: -url=jdbc:postgresql://postgres-flyway-1:5432/flyway_test_db -user=postgres -password=Mohammad -locations=filesystem:/sql migrate
    volumes:
      - ./sql:/sql  # Mount your SQL migration files
    depends_on:
      - postgres-flyway
