name: Flyway Migrate

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flyway-migrate:
    runs-on: windows-latest  # Use Windows as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Java (Flyway requires Java to run)
    - name: Set up JDK (if needed for Flyway)
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Specify your Java version if needed for Flyway

    # Install Flyway on Windows
    - name: Install Flyway
      run: |
        Invoke-WebRequest -Uri "https://flywaydb.org/download/community/latest" -OutFile "flyway.zip"
        Expand-Archive -Path "flyway.zip" -DestinationPath "flyway"
        Move-Item -Path "flyway" -Destination "C:\flyway"

    # Run Flyway Migrate
    - name: Run Flyway Migrate
      run: |
        C:\flyway\flyway -configFiles=flyway.conf migrate
